### ISSUE TITLE
企业微信机器人测试发送失败

### ISSUE THREAD

**Issue by nondevops** [n9e/wechatrobot-sender#1]
问题描述:
企业微信机器人测试发送失败

截图:
![image](https://user-images.githubusercontent.com/12181410/88066269-27228100-cba0-11ea-83ab-707387f02c31.png)
![image](https://user-images.githubusercontent.com/12181410/88066395-4c16f400-cba0-11ea-8bb9-acc6000d864f.png)
![image](https://user-images.githubusercontent.com/12181410/88066583-7ff21980-cba0-11ea-924c-6125343fc428.png)

@710leo @UlricQin 麻烦看看是否配置有问题导致的,实在看不出来哪里有问题,谢谢

**Comment by nondevops** [comment]
touser 需要改成企业微信机器人的token才能发送

**Comment by DingGuodong** [comment]
就企业微信应用发送消息的设计而言，应用是支持通过agentid和secret发送给应用范围内所有人（任何人的），我认为这是一个bug，应该reopen这个issue。因为企业微信应用发送消息支持发送到应用范围内任何人，而不只是发送给企业微信机器人。

**Comment by DingGuodong** [comment]
vim +56 https://github.com/n9e/wechatrobot-sender/blob/master/corp/corp.go

此行代码使用api为："https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key="
建议的使用方式是应该支持：https://qyapi.weixin.qq.com/cgi-bin/message/send?token=<token>

**Comment by UlricQin** [comment]
> vim +56 https://github.com/n9e/wechatrobot-sender/blob/master/corp/corp.go
> 
> 此行代码使用api为："https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key="
> 建议的使用方式是应该支持：https://qyapi.weixin.qq.com/cgi-bin/message/send?token=

这俩api的区别是啥？这个功能也是社区提的，我们不太清楚

**Comment by DingGuodong** [comment]
> > vim +56 https://github.com/n9e/wechatrobot-sender/blob/master/corp/corp.go
> > 此行代码使用api为："https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key="
> > 建议的使用方式是应该支持：https://qyapi.weixin.qq.com/cgi-bin/message/send?token=
> 
> 这俩api的区别是啥？这个功能也是社区提的，我们不太清楚

区别还是很明显的，首先我在此issue中提到过：
> 就企业微信应用发送消息的设计而言，应用是支持通过agentid和secret发送给应用范围内所有人（任何人的），因为企业微信应用发送消息支持发送到应用范围内任何人，而**不只是发送给企业微信机器人**。

如果只是发送给企业微信中的机器人，那还需要额外的配置。不如直接使用群聊机器人的webhook更简单，就不需要创建应用再去写多余的代码和配置了。

所以我的建议是，如果使用应用发送消息模式的话，就直接使用 https://qyapi.weixin.qq.com/cgi-bin/message/send?token= 这个api接口即可。

参考链接：[发送应用消息](https://work.weixin.qq.com/api/doc/90000/90135/90236)

**Comment by UlricQin** [comment]
赞，来个PR？ @DingGuodong

**Comment by DingGuodong** [comment]
> 赞，来个PR？ @DingGuodong

非常惭愧啊，本来非常想帮忙一下，但我不会golang，只会python，PHP等脚本语言。
